[package]
name = "rtsched"
version = "0.1.0"
authors = ["Kwangdo Yi <kwangdo.yi@gmail.com>"]
edition = "2024"
rust-version = "1.85"
description = "A no_std runtime scheduler for Cortex-M thread management"
license = "MIT"
repository = "https://github.com/chungae9ri/rtsched"
documentation = "https://docs.rs/rtsched"
keywords = ["scheduler", "embedded", "cortex-m", "no-std", "rtos"]
categories = ["embedded", "no-std", "os"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/examples/**",
    "/src/**",
]

[lib]
name = "rtsched"
bench = false

[features]
embedded-examples = []
sched-isr-timing = []

[dependencies]
cortex-m = "0.7.7"

[dev-dependencies]
cortex-m-rt = "0.6.15"

[[example]]
name = "minimal_cfs"
path = "examples/minimal_cfs.rs"
test = false
bench = false
required-features = ["embedded-examples"]

[[example]]
name = "minimal_rt"
path = "examples/minimal_rt.rs"
test = false
bench = false
required-features = ["embedded-examples"]

[[example]]
name = "mixed_rt_cfs"
path = "examples/mixed_rt_cfs.rs"
test = false
bench = false
required-features = ["embedded-examples"]

[[example]]
name = "sleep_wake"
path = "examples/sleep_wake.rs"
test = false
bench = false
required-features = ["embedded-examples"]

[[example]]
name = "sync_binary_semaphore"
path = "examples/sync_binary_semaphore.rs"
test = false
bench = false
required-features = ["embedded-examples"]

[[example]]
name = "sync_counting_semaphore"
path = "examples/sync_counting_semaphore.rs"
test = false
bench = false
required-features = ["embedded-examples"]

[[example]]
name = "sync_mutex"
path = "examples/sync_mutex.rs"
test = false
bench = false
required-features = ["embedded-examples"]
