name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_BUILD_TARGET: thumbv8m.main-none-eabihf

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust target
      run: rustup target add ${{ env.CARGO_BUILD_TARGET }}
    - name: Build
      run: cargo build --verbose --target ${{ env.CARGO_BUILD_TARGET }}
    - name: Check examples
      run: cargo check --examples --features embedded-examples --target ${{ env.CARGO_BUILD_TARGET }}
    - name: Run tests
      run: cargo test-host
